/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const SupportConversationId = IDL.Text;
export const SupportMessageId = IDL.Text;
export const SupportSenderType = IDL.Variant({
  'user' : IDL.Null,
  'platformAdmin' : IDL.Null,
});
export const SupportMessage = IDL.Record({
  'id' : SupportMessageId,
  'senderUserName' : IDL.Text,
  'createdAt' : IDL.Int,
  'conversationId' : SupportConversationId,
  'message' : IDL.Text,
  'senderType' : SupportSenderType,
  'senderUserId' : IDL.Text,
  'readAt' : IDL.Opt(IDL.Int),
});
export const Result_27 = IDL.Variant({
  'ok' : SupportMessage,
  'err' : IDL.Text,
});
export const ZahlungId = IDL.Text;
export const ZahlungEingangStatus = IDL.Variant({
  'eingegangen' : IDL.Null,
  'bestaetigt' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const RechnungId = IDL.Text;
export const KanzleiId = IDL.Text;
export const Zahlung = IDL.Record({
  'id' : ZahlungId,
  'status' : ZahlungEingangStatus,
  'createdAt' : Timestamp,
  'rechnungId' : RechnungId,
  'betrag' : IDL.Nat,
  'datum' : IDL.Text,
  'kanzleiId' : KanzleiId,
});
export const Result_26 = IDL.Variant({ 'ok' : Zahlung, 'err' : IDL.Text });
export const PendingRegistrationId = IDL.Text;
export const VerificationError = IDL.Variant({
  'codeExpired' : IDL.Null,
  'tooManyAttempts' : IDL.Null,
  'principalAlreadyUsed' : IDL.Null,
  'invalidInput' : IDL.Null,
  'sendFailed' : IDL.Null,
  'notFound' : IDL.Null,
  'invalidCode' : IDL.Null,
  'alreadyRegistered' : IDL.Null,
  'emailAlreadyVerified' : IDL.Null,
  'resendTooSoon' : IDL.Null,
});
export const Result = IDL.Variant({
  'ok' : IDL.Null,
  'err' : VerificationError,
});
export const Result_25 = IDL.Variant({
  'ok' : KanzleiId,
  'err' : VerificationError,
});
export const AuslagenKategorie = IDL.Variant({
  'andere' : IDL.Null,
  'porto' : IDL.Null,
  'reise' : IDL.Null,
  'kopien' : IDL.Null,
});
export const AuslageId = IDL.Text;
export const AuslagenStatus = IDL.Variant({
  'offen' : IDL.Null,
  'verrechnet' : IDL.Null,
});
export const MandatId = IDL.Text;
export const Auslage = IDL.Record({
  'id' : AuslageId,
  'status' : AuslagenStatus,
  'createdAt' : Timestamp,
  'leistungserbringerId' : IDL.Principal,
  'rechnungId' : IDL.Opt(RechnungId),
  'betrag' : IDL.Nat,
  'kategorie' : AuslagenKategorie,
  'beschreibung' : IDL.Text,
  'datum' : IDL.Text,
  'mandatId' : MandatId,
  'kanzleiId' : KanzleiId,
});
export const Result_12 = IDL.Variant({ 'ok' : Auslage, 'err' : IDL.Text });
export const DsrId = IDL.Text;
export const DsrStatus = IDL.Variant({
  'inBearbeitung' : IDL.Null,
  'abgeschlossen' : IDL.Null,
  'erfasst' : IDL.Null,
});
export const DsrType = IDL.Variant({
  'berichtigung' : IDL.Null,
  'loeschung' : IDL.Null,
  'auskunft' : IDL.Null,
});
export const KlientId = IDL.Text;
export const DsrRequest = IDL.Record({
  'id' : DsrId,
  'status' : DsrStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'dsrType' : DsrType,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'requesterEmail' : IDL.Text,
  'requesterName' : IDL.Text,
  'kanzleiId' : KanzleiId,
  'requesterId' : IDL.Opt(KlientId),
});
export const Result_17 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Klient = IDL.Record({
  'id' : KlientId,
  'plzOrt' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'telefon' : IDL.Text,
  'kanzleiId' : KanzleiId,
  'strasse' : IDL.Text,
});
export const Result_7 = IDL.Variant({ 'ok' : Klient, 'err' : IDL.Text });
export const LeistungId = IDL.Text;
export const LeistungStatus = IDL.Variant({
  'offen' : IDL.Null,
  'verrechnet' : IDL.Null,
});
export const Leistung = IDL.Record({
  'id' : LeistungId,
  'status' : LeistungStatus,
  'taetigkeit' : IDL.Text,
  'createdAt' : Timestamp,
  'leistungserbringerId' : IDL.Principal,
  'rechnungId' : IDL.Opt(RechnungId),
  'datum' : IDL.Text,
  'dauer' : IDL.Nat,
  'honorar' : IDL.Nat,
  'mandatId' : MandatId,
  'kanzleiId' : KanzleiId,
});
export const Result_6 = IDL.Variant({ 'ok' : Leistung, 'err' : IDL.Text });
export const Auslagenregelung = IDL.Variant({
  'Effektiv' : IDL.Null,
  'Keine' : IDL.Null,
  'Pauschal' : IDL.Null,
});
export const MandatStatus = IDL.Variant({
  'archiviert' : IDL.Null,
  'aktiv' : IDL.Null,
});
export const Mandat = IDL.Record({
  'id' : MandatId,
  'status' : MandatStatus,
  'rundungAktiv' : IDL.Bool,
  'bezeichnung' : IDL.Text,
  'kostenProScan' : IDL.Float64,
  'auslagenregelung' : Auslagenregelung,
  'createdAt' : Timestamp,
  'kostenProKopie' : IDL.Float64,
  'leistungenAusweisen' : IDL.Bool,
  'portoEinschreiben' : IDL.Float64,
  'portoBPost' : IDL.Float64,
  'akquisitionsbonus' : IDL.Nat,
  'pauschalBetrag' : IDL.Nat,
  'mwstSatz' : IDL.Nat,
  'standardStundensatz' : IDL.Nat,
  'zahlungsbedingungen' : IDL.Text,
  'akquisiteurId' : IDL.Principal,
  'budget' : IDL.Nat,
  'autokilometer' : IDL.Float64,
  'klientId' : KlientId,
  'waehrung' : IDL.Text,
  'portoAPost' : IDL.Float64,
  'kanzleiId' : KanzleiId,
});
export const Result_5 = IDL.Variant({ 'ok' : Mandat, 'err' : IDL.Text });
export const ZahlungsStatus = IDL.Variant({
  'offen' : IDL.Null,
  'bezahlt' : IDL.Null,
  'ueberfaellig' : IDL.Null,
});
export const Rechnung = IDL.Record({
  'id' : RechnungId,
  'rechnungsnummer' : IDL.Text,
  'total' : IDL.Nat,
  'rechnungsdatum' : IDL.Text,
  'createdAt' : Timestamp,
  'mwstBetrag' : IDL.Nat,
  'leistungserbringerId' : IDL.Principal,
  'faelligkeitsdatum' : IDL.Text,
  'zahlungsstatus' : ZahlungsStatus,
  'zahlungsbedingungen' : IDL.Text,
  'leistungszeitraumBis' : IDL.Text,
  'leistungszeitraumVon' : IDL.Text,
  'leistungspositionen' : IDL.Vec(LeistungId),
  'auslageIds' : IDL.Vec(AuslageId),
  'waehrung' : IDL.Text,
  'mandatId' : MandatId,
  'kanzleiId' : KanzleiId,
  'subtotal' : IDL.Nat,
});
export const Result_24 = IDL.Variant({ 'ok' : Rechnung, 'err' : IDL.Text });
export const SupportCategory = IDL.Variant({
  'frage' : IDL.Null,
  'fehler' : IDL.Null,
  'feedback' : IDL.Null,
  'verbesserungsvorschlag' : IDL.Null,
});
export const SupportStatus = IDL.Variant({
  'neu' : IDL.Null,
  'archiviert' : IDL.Null,
  'erledigt' : IDL.Null,
  'in_bearbeitung' : IDL.Null,
});
export const SupportConversation = IDL.Record({
  'id' : SupportConversationId,
  'status' : SupportStatus,
  'appRoute' : IDL.Text,
  'subject' : IDL.Text,
  'createdByUserId' : IDL.Text,
  'createdAt' : IDL.Int,
  'appVersion' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : SupportCategory,
  'kanzleiId' : KanzleiId,
  'createdByUserName' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : SupportConversation,
  'err' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AuditTrailFilter = IDL.Record({
  'toTimestamp' : IDL.Opt(Timestamp),
  'fromTimestamp' : IDL.Opt(Timestamp),
  'entityId' : IDL.Opt(IDL.Text),
  'actorPrincipal' : IDL.Opt(IDL.Principal),
  'entityType' : IDL.Opt(IDL.Text),
  'kanzleiId' : KanzleiId,
});
export const ActiveUserEntry = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const ActiveUserMonth = IDL.Record({
  'month' : IDL.Nat,
  'total' : IDL.Int,
  'year' : IDL.Nat,
  'users' : IDL.Vec(ActiveUserEntry),
});
export const ActiveUsersYearReport = IDL.Record({
  'yearTotal' : IDL.Int,
  'year' : IDL.Nat,
  'months' : IDL.Vec(ActiveUserMonth),
  'kanzleiId' : KanzleiId,
});
export const AllKanzleienActiveUsersReport = IDL.Record({
  'kanzleiName' : IDL.Text,
  'yearTotal' : IDL.Int,
  'year' : IDL.Nat,
  'months' : IDL.Vec(ActiveUserMonth),
  'kanzleiId' : KanzleiId,
});
export const BillingStatus = IDL.Variant({
  'offen' : IDL.Null,
  'bezahlt' : IDL.Null,
  'ueberfaellig' : IDL.Null,
});
export const AboModell = IDL.Variant({
  'jahres' : IDL.Null,
  'monats' : IDL.Null,
  'keine' : IDL.Null,
});
export const KanzleiOverview = IDL.Record({
  'id' : KanzleiId,
  'stammdatenAdresse' : IDL.Text,
  'status' : IDL.Text,
  'billingStatus' : BillingStatus,
  'stammdatenMwstNr' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'stammdatenUid' : IDL.Text,
  'stammdatenKanzleiname' : IDL.Text,
  'aboModell' : AboModell,
  'userCount' : IDL.Nat,
});
export const Result_23 = IDL.Variant({
  'ok' : IDL.Vec(SupportConversation),
  'err' : IDL.Text,
});
export const AuditLogId = IDL.Text;
export const AuditLogEntry = IDL.Record({
  'id' : AuditLogId,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'afterValue' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'beforeValue' : IDL.Opt(IDL.Text),
  'actorPrincipal' : IDL.Principal,
  'entityType' : IDL.Text,
  'kanzleiId' : KanzleiId,
});
export const AuslagenFilter = IDL.Record({
  'status' : IDL.Opt(AuslagenStatus),
  'datumBis' : IDL.Opt(IDL.Text),
  'datumVon' : IDL.Opt(IDL.Text),
  'leistungserbringerId' : IDL.Opt(IDL.Principal),
  'mandatId' : IDL.Opt(MandatId),
});
export const BudgetSummary = IDL.Record({
  'restbudget' : IDL.Int,
  'totalAuslagen' : IDL.Nat,
  'totalHonorar' : IDL.Nat,
  'totalBudget' : IDL.Nat,
  'mandatId' : MandatId,
});
export const Result_22 = IDL.Variant({
  'ok' : BudgetSummary,
  'err' : IDL.Text,
});
export const ConsentId = IDL.Text;
export const ConsentRecord = IDL.Record({
  'id' : ConsentId,
  'principal' : IDL.Principal,
  'dsgVersion' : IDL.Text,
  'timestamp' : Timestamp,
  'consentGiven' : IDL.Bool,
  'klientId' : KlientId,
  'kanzleiId' : KanzleiId,
});
export const Role = IDL.Variant({
  'mandant' : IDL.Null,
  'admin' : IDL.Null,
  'mitarbeiter' : IDL.Null,
  'plattform_admin' : IDL.Null,
  'anwalt' : IDL.Null,
});
export const StatusHistoryEntry = IDL.Record({
  'status' : IDL.Text,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const Leistungserbringer = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Text,
  'titel' : IDL.Text,
  'nachname' : IDL.Text,
  'role' : IDL.Opt(Role),
  'statusHistory' : IDL.Vec(StatusHistoryEntry),
  'email' : IDL.Text,
  'vorname' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'registeredAt' : Timestamp,
  'kanzleiId' : KanzleiId,
});
export const DashboardStats = IDL.Record({
  'pendingDeletions' : IDL.Nat,
  'auditExports' : IDL.Nat,
  'totalRecordsByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'openDsrRequests' : IDL.Nat,
  'missingConsents' : IDL.Nat,
});
export const DataFlowId = IDL.Text;
export const DataFlowEntry = IDL.Record({
  'id' : DataFlowId,
  'destination' : IDL.Text,
  'what' : IDL.Text,
  'isExternal' : IDL.Bool,
  'flowName' : IDL.Text,
  'legalBasis' : IDL.Text,
  'purpose' : IDL.Text,
  'kanzleiId' : KanzleiId,
});
export const DataInventoryId = IDL.Text;
export const DataInventoryEntry = IDL.Record({
  'id' : DataInventoryId,
  'storageDuration' : IDL.Text,
  'categoryName' : IDL.Text,
  'accessRole' : Role,
  'description' : IDL.Opt(IDL.Text),
  'storageLocation' : IDL.Text,
  'kanzleiId' : KanzleiId,
});
export const DsgVersion = IDL.Record({
  'content' : IDL.Opt(IDL.Text),
  'publishedAt' : Timestamp,
  'version' : IDL.Text,
});
export const GehaltInfo = IDL.Record({
  'leistungsbasiert' : IDL.Nat,
  'kanzleianteil' : IDL.Nat,
  'provider' : Leistungserbringer,
  'gesamtgehalt' : IDL.Nat,
  'akquisitionsboni' : IDL.Nat,
});
export const InviteToken = IDL.Record({
  'redeemedBy' : IDL.Opt(IDL.Principal),
  'token' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'kanzleiId' : KanzleiId,
});
export const KanzleiStammdaten = IDL.Record({
  'ort' : IDL.Text,
  'plz' : IDL.Text,
  'uid' : IDL.Text,
  'land' : IDL.Text,
  'kanzleiname' : IDL.Text,
  'strasseHausnummer' : IDL.Text,
  'kanzleiLogoBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'mwstNr' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'telefon' : IDL.Text,
});
export const Zahlungsmodalitaet = IDL.Variant({
  'jahres' : IDL.Null,
  'monats' : IDL.Null,
});
export const Kanzlei = IDL.Record({
  'id' : KanzleiId,
  'defaultStundensatz' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'stammdaten' : IDL.Opt(KanzleiStammdaten),
  'zahlungsmodalitaet' : IDL.Opt(Zahlungsmodalitaet),
});
export const ReportPeriod = IDL.Variant({
  'monatlich' : IDL.Nat,
  'jaehrlich' : IDL.Null,
});
export const MonthlyTotal = IDL.Record({
  'month' : IDL.Nat,
  'total' : IDL.Nat,
  'auslagen' : IDL.Nat,
  'year' : IDL.Nat,
  'verrechnete' : IDL.Nat,
  'honorar' : IDL.Nat,
});
export const FirmReport = IDL.Record({
  'monthlyBreakdown' : IDL.Vec(MonthlyTotal),
  'totals' : MonthlyTotal,
});
export const LeistungFilter = IDL.Record({
  'status' : IDL.Opt(LeistungStatus),
  'datumBis' : IDL.Opt(IDL.Text),
  'datumVon' : IDL.Opt(IDL.Text),
  'leistungserbringerId' : IDL.Opt(IDL.Principal),
  'mandatId' : IDL.Opt(MandatId),
});
export const ProviderComparison = IDL.Record({
  'total' : IDL.Nat,
  'provider' : Leistungserbringer,
});
export const ProviderReport = IDL.Record({
  'monthlyBreakdown' : IDL.Vec(MonthlyTotal),
  'totals' : MonthlyTotal,
  'comparisonData' : IDL.Vec(ProviderComparison),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Result_2 = IDL.Variant({
  'ok' : Leistungserbringer,
  'err' : IDL.Text,
});
export const PendingRegistrationView = IDL.Record({
  'id' : PendingRegistrationId,
  'titel' : IDL.Text,
  'nachname' : IDL.Text,
  'emailVerified' : IDL.Bool,
  'kanzleiName' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'vorname' : IDL.Text,
  'zahlungsmodalitaet' : IDL.Opt(Zahlungsmodalitaet),
  'verifiedAt' : IDL.Opt(Timestamp),
});
export const RechnungFilter = IDL.Record({
  'datumBis' : IDL.Opt(IDL.Text),
  'datumVon' : IDL.Opt(IDL.Text),
  'zahlungsstatus' : IDL.Opt(ZahlungsStatus),
  'akquisiteurId' : IDL.Opt(IDL.Principal),
  'mandatId' : IDL.Opt(MandatId),
});
export const Standardtexte = IDL.Record({
  'rechnungstitel' : IDL.Text,
  'zahlungshinweis' : IDL.Text,
  'schlusstext' : IDL.Text,
  'einleitung' : IDL.Text,
});
export const Position = IDL.Variant({
  'zentriert' : IDL.Null,
  'links' : IDL.Null,
  'rechts' : IDL.Null,
});
export const VorlageLayout = IDL.Record({
  'logoPosition' : Position,
  'empfaengerPosition' : Position,
  'fusszeile' : IDL.Text,
  'absenderPosition' : Position,
});
export const LayoutElementId = IDL.Variant({
  'summenblock' : IDL.Null,
  'absenderadresse' : IDL.Null,
  'spesenAuslagen' : IDL.Null,
  'rechnungsmetadaten' : IDL.Null,
  'logo' : IDL.Null,
  'mandatsinfo' : IDL.Null,
  'fusszeile' : IDL.Null,
  'schlusstext' : IDL.Null,
  'einleitung' : IDL.Null,
  'empfaengeradresse' : IDL.Null,
  'leistungspositionen' : IDL.Null,
  'zahlungsinformationen' : IDL.Null,
});
export const GridArea = IDL.Record({
  'col' : IDL.Nat,
  'row' : IDL.Nat,
  'rowSpan' : IDL.Nat,
  'colSpan' : IDL.Nat,
});
export const LayoutElement = IDL.Record({
  'id' : LayoutElementId,
  'xMm' : IDL.Opt(IDL.Float64),
  'yMm' : IDL.Opt(IDL.Float64),
  'italic' : IDL.Opt(IDL.Bool),
  'widthMm' : IDL.Opt(IDL.Float64),
  'heightMm' : IDL.Opt(IDL.Float64),
  'order' : IDL.Nat,
  'bold' : IDL.Opt(IDL.Bool),
  'gridArea' : GridArea,
  'zOrder' : IDL.Opt(IDL.Nat),
  'fontFamily' : IDL.Opt(IDL.Text),
  'visible' : IDL.Bool,
  'fontSize' : IDL.Opt(IDL.Nat),
  'alignment' : IDL.Opt(Position),
});
export const VorlageLayoutV2 = IDL.Record({
  'marginBottomMm' : IDL.Float64,
  'pageHeightMm' : IDL.Float64,
  'gridCols' : IDL.Nat,
  'gridRows' : IDL.Nat,
  'marginRightMm' : IDL.Float64,
  'marginTopMm' : IDL.Float64,
  'marginLeftMm' : IDL.Float64,
  'elements' : IDL.Vec(LayoutElement),
  'pageWidthMm' : IDL.Float64,
});
export const Rechnungsvorlage = IDL.Record({
  'standardtexte' : Standardtexte,
  'layout' : VorlageLayout,
  'logoBlob' : IDL.Opt(ExternalBlob),
  'layoutV2' : IDL.Opt(VorlageLayoutV2),
  'updatedAt' : Timestamp,
  'kanzleiId' : KanzleiId,
});
export const RetentionPolicyId = IDL.Text;
export const RetentionPolicy = IDL.Record({
  'id' : RetentionPolicyId,
  'retentionYears' : IDL.Nat,
  'categoryName' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'legalBasis' : IDL.Opt(IDL.Text),
  'isLocked' : IDL.Bool,
  'kanzleiId' : KanzleiId,
});
export const SuperAdminWhitelistEntry = IDL.Record({
  'principal' : IDL.Principal,
  'addedAt' : Timestamp,
});
export const SupportConversationWithMessages = IDL.Record({
  'messages' : IDL.Vec(SupportMessage),
  'conversation' : SupportConversation,
});
export const Result_21 = IDL.Variant({
  'ok' : SupportConversationWithMessages,
  'err' : IDL.Text,
});
export const TimerState = IDL.Record({
  'startTime' : IDL.Int,
  'userId' : IDL.Principal,
  'leistungId' : LeistungId,
  'baseDauer' : IDL.Nat,
});
export const Result_13 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result_20 = IDL.Variant({ 'ok' : Role, 'err' : IDL.Text });
export const DataAccessAction = IDL.Variant({
  'loeschen' : IDL.Null,
  'lesen' : IDL.Null,
  'schreiben' : IDL.Null,
});
export const RoleMigrationResult = IDL.Record({
  'principal' : IDL.Principal,
  'changed' : IDL.Bool,
  'previousRole' : Role,
  'newRole' : Role,
});
export const MigrationSummary = IDL.Record({
  'convertedCount' : IDL.Nat,
  'results' : IDL.Vec(RoleMigrationResult),
  'unchangedCount' : IDL.Nat,
});
export const Result_19 = IDL.Variant({
  'ok' : MigrationSummary,
  'err' : IDL.Text,
});
export const PromotionResult = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'whitelistAdded' : IDL.Bool,
  'email' : IDL.Text,
  'changed' : IDL.Bool,
});
export const Result_18 = IDL.Variant({
  'ok' : PromotionResult,
  'err' : IDL.Text,
});
export const Result_16 = IDL.Variant({
  'ok' : Rechnungsvorlage,
  'err' : IDL.Text,
});
export const Result_15 = IDL.Variant({
  'ok' : PendingRegistrationId,
  'err' : VerificationError,
});
export const Result_14 = IDL.Variant({ 'ok' : TimerState, 'err' : IDL.Text });
export const Result_11 = IDL.Variant({
  'ok' : DataFlowEntry,
  'err' : IDL.Text,
});
export const Result_10 = IDL.Variant({
  'ok' : DataInventoryEntry,
  'err' : IDL.Text,
});
export const Result_9 = IDL.Variant({ 'ok' : DsrRequest, 'err' : IDL.Text });
export const Result_8 = IDL.Variant({
  'ok' : KanzleiStammdaten,
  'err' : IDL.Text,
});
export const Result_4 = IDL.Variant({
  'ok' : RetentionPolicy,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSuperAdmin' : IDL.Func([IDL.Principal], [Result_1], []),
  'addSupportMessage' : IDL.Func(
      [SupportConversationId, IDL.Text],
      [Result_27],
      [],
    ),
  'addZahlung' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_26], []),
  'archivierMandat' : IDL.Func([IDL.Text], [Result_1], []),
  'changeEmail' : IDL.Func([PendingRegistrationId, IDL.Text], [Result], []),
  'completeRegistration' : IDL.Func([PendingRegistrationId], [Result_25], []),
  'createAuslage' : IDL.Func(
      [IDL.Text, IDL.Text, AuslagenKategorie, IDL.Nat, IDL.Text],
      [Result_12],
      [],
    ),
  'createDsrRequest' : IDL.Func([DsrRequest], [DsrRequest], []),
  'createInviteLink' : IDL.Func([IDL.Text], [Result_17], []),
  'createKlient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_7],
      [],
    ),
  'createLeistung' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_6],
      [],
    ),
  'createMandat' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        Auslagenregelung,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
      ],
      [Result_5],
      [],
    ),
  'createRechnung' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result_24],
      [],
    ),
  'createSupportConversation' : IDL.Func(
      [SupportCategory, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_3],
      [],
    ),
  'deactivateKanzlei' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteAuslage' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteKanzlei' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteKlient' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteLeistung' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteLeistungserbringer' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteMandat' : IDL.Func([IDL.Text], [Result_1], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'executeDeletion' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'exportAuditTrailCsv' : IDL.Func([AuditTrailFilter], [IDL.Text], ['query']),
  'exportAuditTrailPdf' : IDL.Func(
      [AuditTrailFilter],
      [IDL.Vec(IDL.Nat8)],
      ['query'],
    ),
  'exportKanzleienCsv' : IDL.Func([], [IDL.Text], ['query']),
  'exportKanzleienPdf' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'getActiveUsersPerMonth' : IDL.Func(
      [KanzleiId, IDL.Nat],
      [ActiveUsersYearReport],
      ['query'],
    ),
  'getAllActiveUsersPerMonth' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AllKanzleienActiveUsersReport)],
      ['query'],
    ),
  'getAllKanzleienOverview' : IDL.Func(
      [],
      [IDL.Vec(KanzleiOverview)],
      ['query'],
    ),
  'getAllSupportConversations' : IDL.Func([], [Result_23], []),
  'getAuditTrail' : IDL.Func(
      [AuditTrailFilter],
      [IDL.Vec(AuditLogEntry)],
      ['query'],
    ),
  'getAuslagen' : IDL.Func([AuslagenFilter], [IDL.Vec(Auslage)], ['query']),
  'getBudgetSummaries' : IDL.Func([], [IDL.Vec(BudgetSummary)], ['query']),
  'getBudgetSummary' : IDL.Func([MandatId], [Result_22], ['query']),
  'getConsentRecords' : IDL.Func(
      [KanzleiId],
      [IDL.Vec(ConsentRecord)],
      ['query'],
    ),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(Leistungserbringer)], ['query']),
  'getDashboardStats' : IDL.Func([KanzleiId], [DashboardStats], ['query']),
  'getDataFlows' : IDL.Func([KanzleiId], [IDL.Vec(DataFlowEntry)], ['query']),
  'getDataInventory' : IDL.Func(
      [KanzleiId],
      [IDL.Vec(DataInventoryEntry)],
      ['query'],
    ),
  'getDsgVersion' : IDL.Func([], [IDL.Opt(DsgVersion)], ['query']),
  'getDsrRequests' : IDL.Func([KanzleiId], [IDL.Vec(DsrRequest)], ['query']),
  'getGehaltReport' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(GehaltInfo)],
      ['query'],
    ),
  'getInviteLinks' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
  'getKanzlei' : IDL.Func([], [IDL.Opt(Kanzlei)], ['query']),
  'getKanzleiReport' : IDL.Func(
      [IDL.Nat, ReportPeriod],
      [FirmReport],
      ['query'],
    ),
  'getKanzleiStammdaten' : IDL.Func(
      [],
      [IDL.Opt(KanzleiStammdaten)],
      ['query'],
    ),
  'getKlient' : IDL.Func([IDL.Text], [IDL.Opt(Klient)], ['query']),
  'getKlienten' : IDL.Func([], [IDL.Vec(Klient)], ['query']),
  'getLeistungen' : IDL.Func([LeistungFilter], [IDL.Vec(Leistung)], ['query']),
  'getLeistungserbringer' : IDL.Func(
      [],
      [IDL.Vec(Leistungserbringer)],
      ['query'],
    ),
  'getLeistungserbringerByKanzlei' : IDL.Func(
      [KanzleiId],
      [IDL.Vec(Leistungserbringer)],
      ['query'],
    ),
  'getLeistungserbringerReport' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Nat, ReportPeriod],
      [ProviderReport],
      ['query'],
    ),
  'getLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMandat' : IDL.Func([IDL.Text], [IDL.Opt(Mandat)], ['query']),
  'getMandate' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Mandat)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getMySupportConversations' : IDL.Func(
      [],
      [IDL.Vec(SupportConversation)],
      [],
    ),
  'getOrCreateUser' : IDL.Func([], [Result_2], []),
  'getPendingDeletions' : IDL.Func(
      [KanzleiId],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPendingRegistration' : IDL.Func(
      [PendingRegistrationId],
      [IDL.Opt(PendingRegistrationView)],
      ['query'],
    ),
  'getRechnung' : IDL.Func([IDL.Text], [IDL.Opt(Rechnung)], ['query']),
  'getRechnungen' : IDL.Func([RechnungFilter], [IDL.Vec(Rechnung)], ['query']),
  'getRechnungsvorlage' : IDL.Func([], [IDL.Opt(Rechnungsvorlage)], ['query']),
  'getRetentionPolicies' : IDL.Func(
      [KanzleiId],
      [IDL.Vec(RetentionPolicy)],
      ['query'],
    ),
  'getSuperAdmins' : IDL.Func(
      [],
      [IDL.Vec(SuperAdminWhitelistEntry)],
      ['query'],
    ),
  'getSupportConversation' : IDL.Func([SupportConversationId], [Result_21], []),
  'getTimer' : IDL.Func([LeistungId], [IDL.Opt(TimerState)], ['query']),
  'getUnreadSupportCountForAdmin' : IDL.Func([], [Result_13], []),
  'getUnreadSupportCountForUser' : IDL.Func([], [IDL.Nat], []),
  'getUserRole' : IDL.Func([IDL.Principal], [Result_20], ['query']),
  'getZahlungen' : IDL.Func([], [IDL.Vec(Zahlung)], ['query']),
  'isSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTimers' : IDL.Func([], [IDL.Vec(TimerState)], ['query']),
  'logAuditEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'logDataAccess' : IDL.Func([IDL.Text, IDL.Text, DataAccessAction], [], []),
  'markSupportMessageRead' : IDL.Func([SupportConversationId], [Result_1], []),
  'migrateRoles' : IDL.Func([], [Result_19], []),
  'promoteJoaoMarques' : IDL.Func([], [Result_18], []),
  'reactivateKanzlei' : IDL.Func([IDL.Text], [Result_1], []),
  'recordConsent' : IDL.Func([KlientId, IDL.Text], [ConsentRecord], []),
  'redeemInviteLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'registerKanzlei' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(Zahlungsmodalitaet),
      ],
      [Result_17],
      [],
    ),
  'removeLeistungserbringer' : IDL.Func([IDL.Principal], [Result_1], []),
  'removeLogo' : IDL.Func([], [Result_1], []),
  'removeSuperAdmin' : IDL.Func([IDL.Principal], [Result_1], []),
  'saveRechnungsvorlage' : IDL.Func([Rechnungsvorlage], [Result_16], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendVerificationCode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(Zahlungsmodalitaet),
      ],
      [Result_15],
      [],
    ),
  'startTimer' : IDL.Func([LeistungId, IDL.Nat], [Result_14], []),
  'stopTimer' : IDL.Func([LeistungId], [Result_13], []),
  'updateAuslage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_12], []),
  'updateDataFlowEntry' : IDL.Func(
      [DataFlowId, DataFlowEntry],
      [Result_11],
      [],
    ),
  'updateDataInventoryEntry' : IDL.Func(
      [DataInventoryId, DataInventoryEntry],
      [Result_10],
      [],
    ),
  'updateDsgVersion' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [DsgVersion],
      [],
    ),
  'updateDsrRequest' : IDL.Func(
      [DsrId, DsrStatus, IDL.Opt(IDL.Text)],
      [Result_9],
      [],
    ),
  'updateKanzleiStammdaten' : IDL.Func([KanzleiStammdaten], [Result_8], []),
  'updateKanzleiStundensatz' : IDL.Func([IDL.Nat], [Result_1], []),
  'updateKlient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_7],
      [],
    ),
  'updateLeistung' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_6], []),
  'updateLeistungserbringer' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'updateMandat' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        Auslagenregelung,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
      ],
      [Result_5],
      [],
    ),
  'updateRetentionPolicy' : IDL.Func(
      [RetentionPolicyId, IDL.Nat, IDL.Bool],
      [Result_4],
      [],
    ),
  'updateSupportStatus' : IDL.Func(
      [SupportConversationId, SupportStatus],
      [Result_3],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'updateUserRole' : IDL.Func([IDL.Principal, Role], [Result_2], []),
  'updateZahlungsstatus' : IDL.Func([IDL.Text, ZahlungsStatus], [Result_1], []),
  'uploadLogo' : IDL.Func([ExternalBlob], [Result_1], []),
  'verifyEmail' : IDL.Func([PendingRegistrationId, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SupportConversationId = IDL.Text;
  const SupportMessageId = IDL.Text;
  const SupportSenderType = IDL.Variant({
    'user' : IDL.Null,
    'platformAdmin' : IDL.Null,
  });
  const SupportMessage = IDL.Record({
    'id' : SupportMessageId,
    'senderUserName' : IDL.Text,
    'createdAt' : IDL.Int,
    'conversationId' : SupportConversationId,
    'message' : IDL.Text,
    'senderType' : SupportSenderType,
    'senderUserId' : IDL.Text,
    'readAt' : IDL.Opt(IDL.Int),
  });
  const Result_27 = IDL.Variant({ 'ok' : SupportMessage, 'err' : IDL.Text });
  const ZahlungId = IDL.Text;
  const ZahlungEingangStatus = IDL.Variant({
    'eingegangen' : IDL.Null,
    'bestaetigt' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const RechnungId = IDL.Text;
  const KanzleiId = IDL.Text;
  const Zahlung = IDL.Record({
    'id' : ZahlungId,
    'status' : ZahlungEingangStatus,
    'createdAt' : Timestamp,
    'rechnungId' : RechnungId,
    'betrag' : IDL.Nat,
    'datum' : IDL.Text,
    'kanzleiId' : KanzleiId,
  });
  const Result_26 = IDL.Variant({ 'ok' : Zahlung, 'err' : IDL.Text });
  const PendingRegistrationId = IDL.Text;
  const VerificationError = IDL.Variant({
    'codeExpired' : IDL.Null,
    'tooManyAttempts' : IDL.Null,
    'principalAlreadyUsed' : IDL.Null,
    'invalidInput' : IDL.Null,
    'sendFailed' : IDL.Null,
    'notFound' : IDL.Null,
    'invalidCode' : IDL.Null,
    'alreadyRegistered' : IDL.Null,
    'emailAlreadyVerified' : IDL.Null,
    'resendTooSoon' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : VerificationError });
  const Result_25 = IDL.Variant({
    'ok' : KanzleiId,
    'err' : VerificationError,
  });
  const AuslagenKategorie = IDL.Variant({
    'andere' : IDL.Null,
    'porto' : IDL.Null,
    'reise' : IDL.Null,
    'kopien' : IDL.Null,
  });
  const AuslageId = IDL.Text;
  const AuslagenStatus = IDL.Variant({
    'offen' : IDL.Null,
    'verrechnet' : IDL.Null,
  });
  const MandatId = IDL.Text;
  const Auslage = IDL.Record({
    'id' : AuslageId,
    'status' : AuslagenStatus,
    'createdAt' : Timestamp,
    'leistungserbringerId' : IDL.Principal,
    'rechnungId' : IDL.Opt(RechnungId),
    'betrag' : IDL.Nat,
    'kategorie' : AuslagenKategorie,
    'beschreibung' : IDL.Text,
    'datum' : IDL.Text,
    'mandatId' : MandatId,
    'kanzleiId' : KanzleiId,
  });
  const Result_12 = IDL.Variant({ 'ok' : Auslage, 'err' : IDL.Text });
  const DsrId = IDL.Text;
  const DsrStatus = IDL.Variant({
    'inBearbeitung' : IDL.Null,
    'abgeschlossen' : IDL.Null,
    'erfasst' : IDL.Null,
  });
  const DsrType = IDL.Variant({
    'berichtigung' : IDL.Null,
    'loeschung' : IDL.Null,
    'auskunft' : IDL.Null,
  });
  const KlientId = IDL.Text;
  const DsrRequest = IDL.Record({
    'id' : DsrId,
    'status' : DsrStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'dsrType' : DsrType,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'requesterEmail' : IDL.Text,
    'requesterName' : IDL.Text,
    'kanzleiId' : KanzleiId,
    'requesterId' : IDL.Opt(KlientId),
  });
  const Result_17 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Klient = IDL.Record({
    'id' : KlientId,
    'plzOrt' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'telefon' : IDL.Text,
    'kanzleiId' : KanzleiId,
    'strasse' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : Klient, 'err' : IDL.Text });
  const LeistungId = IDL.Text;
  const LeistungStatus = IDL.Variant({
    'offen' : IDL.Null,
    'verrechnet' : IDL.Null,
  });
  const Leistung = IDL.Record({
    'id' : LeistungId,
    'status' : LeistungStatus,
    'taetigkeit' : IDL.Text,
    'createdAt' : Timestamp,
    'leistungserbringerId' : IDL.Principal,
    'rechnungId' : IDL.Opt(RechnungId),
    'datum' : IDL.Text,
    'dauer' : IDL.Nat,
    'honorar' : IDL.Nat,
    'mandatId' : MandatId,
    'kanzleiId' : KanzleiId,
  });
  const Result_6 = IDL.Variant({ 'ok' : Leistung, 'err' : IDL.Text });
  const Auslagenregelung = IDL.Variant({
    'Effektiv' : IDL.Null,
    'Keine' : IDL.Null,
    'Pauschal' : IDL.Null,
  });
  const MandatStatus = IDL.Variant({
    'archiviert' : IDL.Null,
    'aktiv' : IDL.Null,
  });
  const Mandat = IDL.Record({
    'id' : MandatId,
    'status' : MandatStatus,
    'rundungAktiv' : IDL.Bool,
    'bezeichnung' : IDL.Text,
    'kostenProScan' : IDL.Float64,
    'auslagenregelung' : Auslagenregelung,
    'createdAt' : Timestamp,
    'kostenProKopie' : IDL.Float64,
    'leistungenAusweisen' : IDL.Bool,
    'portoEinschreiben' : IDL.Float64,
    'portoBPost' : IDL.Float64,
    'akquisitionsbonus' : IDL.Nat,
    'pauschalBetrag' : IDL.Nat,
    'mwstSatz' : IDL.Nat,
    'standardStundensatz' : IDL.Nat,
    'zahlungsbedingungen' : IDL.Text,
    'akquisiteurId' : IDL.Principal,
    'budget' : IDL.Nat,
    'autokilometer' : IDL.Float64,
    'klientId' : KlientId,
    'waehrung' : IDL.Text,
    'portoAPost' : IDL.Float64,
    'kanzleiId' : KanzleiId,
  });
  const Result_5 = IDL.Variant({ 'ok' : Mandat, 'err' : IDL.Text });
  const ZahlungsStatus = IDL.Variant({
    'offen' : IDL.Null,
    'bezahlt' : IDL.Null,
    'ueberfaellig' : IDL.Null,
  });
  const Rechnung = IDL.Record({
    'id' : RechnungId,
    'rechnungsnummer' : IDL.Text,
    'total' : IDL.Nat,
    'rechnungsdatum' : IDL.Text,
    'createdAt' : Timestamp,
    'mwstBetrag' : IDL.Nat,
    'leistungserbringerId' : IDL.Principal,
    'faelligkeitsdatum' : IDL.Text,
    'zahlungsstatus' : ZahlungsStatus,
    'zahlungsbedingungen' : IDL.Text,
    'leistungszeitraumBis' : IDL.Text,
    'leistungszeitraumVon' : IDL.Text,
    'leistungspositionen' : IDL.Vec(LeistungId),
    'auslageIds' : IDL.Vec(AuslageId),
    'waehrung' : IDL.Text,
    'mandatId' : MandatId,
    'kanzleiId' : KanzleiId,
    'subtotal' : IDL.Nat,
  });
  const Result_24 = IDL.Variant({ 'ok' : Rechnung, 'err' : IDL.Text });
  const SupportCategory = IDL.Variant({
    'frage' : IDL.Null,
    'fehler' : IDL.Null,
    'feedback' : IDL.Null,
    'verbesserungsvorschlag' : IDL.Null,
  });
  const SupportStatus = IDL.Variant({
    'neu' : IDL.Null,
    'archiviert' : IDL.Null,
    'erledigt' : IDL.Null,
    'in_bearbeitung' : IDL.Null,
  });
  const SupportConversation = IDL.Record({
    'id' : SupportConversationId,
    'status' : SupportStatus,
    'appRoute' : IDL.Text,
    'subject' : IDL.Text,
    'createdByUserId' : IDL.Text,
    'createdAt' : IDL.Int,
    'appVersion' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : SupportCategory,
    'kanzleiId' : KanzleiId,
    'createdByUserName' : IDL.Text,
  });
  const Result_3 = IDL.Variant({
    'ok' : SupportConversation,
    'err' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AuditTrailFilter = IDL.Record({
    'toTimestamp' : IDL.Opt(Timestamp),
    'fromTimestamp' : IDL.Opt(Timestamp),
    'entityId' : IDL.Opt(IDL.Text),
    'actorPrincipal' : IDL.Opt(IDL.Principal),
    'entityType' : IDL.Opt(IDL.Text),
    'kanzleiId' : KanzleiId,
  });
  const ActiveUserEntry = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const ActiveUserMonth = IDL.Record({
    'month' : IDL.Nat,
    'total' : IDL.Int,
    'year' : IDL.Nat,
    'users' : IDL.Vec(ActiveUserEntry),
  });
  const ActiveUsersYearReport = IDL.Record({
    'yearTotal' : IDL.Int,
    'year' : IDL.Nat,
    'months' : IDL.Vec(ActiveUserMonth),
    'kanzleiId' : KanzleiId,
  });
  const AllKanzleienActiveUsersReport = IDL.Record({
    'kanzleiName' : IDL.Text,
    'yearTotal' : IDL.Int,
    'year' : IDL.Nat,
    'months' : IDL.Vec(ActiveUserMonth),
    'kanzleiId' : KanzleiId,
  });
  const BillingStatus = IDL.Variant({
    'offen' : IDL.Null,
    'bezahlt' : IDL.Null,
    'ueberfaellig' : IDL.Null,
  });
  const AboModell = IDL.Variant({
    'jahres' : IDL.Null,
    'monats' : IDL.Null,
    'keine' : IDL.Null,
  });
  const KanzleiOverview = IDL.Record({
    'id' : KanzleiId,
    'stammdatenAdresse' : IDL.Text,
    'status' : IDL.Text,
    'billingStatus' : BillingStatus,
    'stammdatenMwstNr' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'stammdatenUid' : IDL.Text,
    'stammdatenKanzleiname' : IDL.Text,
    'aboModell' : AboModell,
    'userCount' : IDL.Nat,
  });
  const Result_23 = IDL.Variant({
    'ok' : IDL.Vec(SupportConversation),
    'err' : IDL.Text,
  });
  const AuditLogId = IDL.Text;
  const AuditLogEntry = IDL.Record({
    'id' : AuditLogId,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'afterValue' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'beforeValue' : IDL.Opt(IDL.Text),
    'actorPrincipal' : IDL.Principal,
    'entityType' : IDL.Text,
    'kanzleiId' : KanzleiId,
  });
  const AuslagenFilter = IDL.Record({
    'status' : IDL.Opt(AuslagenStatus),
    'datumBis' : IDL.Opt(IDL.Text),
    'datumVon' : IDL.Opt(IDL.Text),
    'leistungserbringerId' : IDL.Opt(IDL.Principal),
    'mandatId' : IDL.Opt(MandatId),
  });
  const BudgetSummary = IDL.Record({
    'restbudget' : IDL.Int,
    'totalAuslagen' : IDL.Nat,
    'totalHonorar' : IDL.Nat,
    'totalBudget' : IDL.Nat,
    'mandatId' : MandatId,
  });
  const Result_22 = IDL.Variant({ 'ok' : BudgetSummary, 'err' : IDL.Text });
  const ConsentId = IDL.Text;
  const ConsentRecord = IDL.Record({
    'id' : ConsentId,
    'principal' : IDL.Principal,
    'dsgVersion' : IDL.Text,
    'timestamp' : Timestamp,
    'consentGiven' : IDL.Bool,
    'klientId' : KlientId,
    'kanzleiId' : KanzleiId,
  });
  const Role = IDL.Variant({
    'mandant' : IDL.Null,
    'admin' : IDL.Null,
    'mitarbeiter' : IDL.Null,
    'plattform_admin' : IDL.Null,
    'anwalt' : IDL.Null,
  });
  const StatusHistoryEntry = IDL.Record({
    'status' : IDL.Text,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const Leistungserbringer = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Text,
    'titel' : IDL.Text,
    'nachname' : IDL.Text,
    'role' : IDL.Opt(Role),
    'statusHistory' : IDL.Vec(StatusHistoryEntry),
    'email' : IDL.Text,
    'vorname' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'registeredAt' : Timestamp,
    'kanzleiId' : KanzleiId,
  });
  const DashboardStats = IDL.Record({
    'pendingDeletions' : IDL.Nat,
    'auditExports' : IDL.Nat,
    'totalRecordsByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'openDsrRequests' : IDL.Nat,
    'missingConsents' : IDL.Nat,
  });
  const DataFlowId = IDL.Text;
  const DataFlowEntry = IDL.Record({
    'id' : DataFlowId,
    'destination' : IDL.Text,
    'what' : IDL.Text,
    'isExternal' : IDL.Bool,
    'flowName' : IDL.Text,
    'legalBasis' : IDL.Text,
    'purpose' : IDL.Text,
    'kanzleiId' : KanzleiId,
  });
  const DataInventoryId = IDL.Text;
  const DataInventoryEntry = IDL.Record({
    'id' : DataInventoryId,
    'storageDuration' : IDL.Text,
    'categoryName' : IDL.Text,
    'accessRole' : Role,
    'description' : IDL.Opt(IDL.Text),
    'storageLocation' : IDL.Text,
    'kanzleiId' : KanzleiId,
  });
  const DsgVersion = IDL.Record({
    'content' : IDL.Opt(IDL.Text),
    'publishedAt' : Timestamp,
    'version' : IDL.Text,
  });
  const GehaltInfo = IDL.Record({
    'leistungsbasiert' : IDL.Nat,
    'kanzleianteil' : IDL.Nat,
    'provider' : Leistungserbringer,
    'gesamtgehalt' : IDL.Nat,
    'akquisitionsboni' : IDL.Nat,
  });
  const InviteToken = IDL.Record({
    'redeemedBy' : IDL.Opt(IDL.Principal),
    'token' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'kanzleiId' : KanzleiId,
  });
  const KanzleiStammdaten = IDL.Record({
    'ort' : IDL.Text,
    'plz' : IDL.Text,
    'uid' : IDL.Text,
    'land' : IDL.Text,
    'kanzleiname' : IDL.Text,
    'strasseHausnummer' : IDL.Text,
    'kanzleiLogoBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'mwstNr' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'telefon' : IDL.Text,
  });
  const Zahlungsmodalitaet = IDL.Variant({
    'jahres' : IDL.Null,
    'monats' : IDL.Null,
  });
  const Kanzlei = IDL.Record({
    'id' : KanzleiId,
    'defaultStundensatz' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'stammdaten' : IDL.Opt(KanzleiStammdaten),
    'zahlungsmodalitaet' : IDL.Opt(Zahlungsmodalitaet),
  });
  const ReportPeriod = IDL.Variant({
    'monatlich' : IDL.Nat,
    'jaehrlich' : IDL.Null,
  });
  const MonthlyTotal = IDL.Record({
    'month' : IDL.Nat,
    'total' : IDL.Nat,
    'auslagen' : IDL.Nat,
    'year' : IDL.Nat,
    'verrechnete' : IDL.Nat,
    'honorar' : IDL.Nat,
  });
  const FirmReport = IDL.Record({
    'monthlyBreakdown' : IDL.Vec(MonthlyTotal),
    'totals' : MonthlyTotal,
  });
  const LeistungFilter = IDL.Record({
    'status' : IDL.Opt(LeistungStatus),
    'datumBis' : IDL.Opt(IDL.Text),
    'datumVon' : IDL.Opt(IDL.Text),
    'leistungserbringerId' : IDL.Opt(IDL.Principal),
    'mandatId' : IDL.Opt(MandatId),
  });
  const ProviderComparison = IDL.Record({
    'total' : IDL.Nat,
    'provider' : Leistungserbringer,
  });
  const ProviderReport = IDL.Record({
    'monthlyBreakdown' : IDL.Vec(MonthlyTotal),
    'totals' : MonthlyTotal,
    'comparisonData' : IDL.Vec(ProviderComparison),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Result_2 = IDL.Variant({ 'ok' : Leistungserbringer, 'err' : IDL.Text });
  const PendingRegistrationView = IDL.Record({
    'id' : PendingRegistrationId,
    'titel' : IDL.Text,
    'nachname' : IDL.Text,
    'emailVerified' : IDL.Bool,
    'kanzleiName' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'vorname' : IDL.Text,
    'zahlungsmodalitaet' : IDL.Opt(Zahlungsmodalitaet),
    'verifiedAt' : IDL.Opt(Timestamp),
  });
  const RechnungFilter = IDL.Record({
    'datumBis' : IDL.Opt(IDL.Text),
    'datumVon' : IDL.Opt(IDL.Text),
    'zahlungsstatus' : IDL.Opt(ZahlungsStatus),
    'akquisiteurId' : IDL.Opt(IDL.Principal),
    'mandatId' : IDL.Opt(MandatId),
  });
  const Standardtexte = IDL.Record({
    'rechnungstitel' : IDL.Text,
    'zahlungshinweis' : IDL.Text,
    'schlusstext' : IDL.Text,
    'einleitung' : IDL.Text,
  });
  const Position = IDL.Variant({
    'zentriert' : IDL.Null,
    'links' : IDL.Null,
    'rechts' : IDL.Null,
  });
  const VorlageLayout = IDL.Record({
    'logoPosition' : Position,
    'empfaengerPosition' : Position,
    'fusszeile' : IDL.Text,
    'absenderPosition' : Position,
  });
  const LayoutElementId = IDL.Variant({
    'summenblock' : IDL.Null,
    'absenderadresse' : IDL.Null,
    'spesenAuslagen' : IDL.Null,
    'rechnungsmetadaten' : IDL.Null,
    'logo' : IDL.Null,
    'mandatsinfo' : IDL.Null,
    'fusszeile' : IDL.Null,
    'schlusstext' : IDL.Null,
    'einleitung' : IDL.Null,
    'empfaengeradresse' : IDL.Null,
    'leistungspositionen' : IDL.Null,
    'zahlungsinformationen' : IDL.Null,
  });
  const GridArea = IDL.Record({
    'col' : IDL.Nat,
    'row' : IDL.Nat,
    'rowSpan' : IDL.Nat,
    'colSpan' : IDL.Nat,
  });
  const LayoutElement = IDL.Record({
    'id' : LayoutElementId,
    'xMm' : IDL.Opt(IDL.Float64),
    'yMm' : IDL.Opt(IDL.Float64),
    'italic' : IDL.Opt(IDL.Bool),
    'widthMm' : IDL.Opt(IDL.Float64),
    'heightMm' : IDL.Opt(IDL.Float64),
    'order' : IDL.Nat,
    'bold' : IDL.Opt(IDL.Bool),
    'gridArea' : GridArea,
    'zOrder' : IDL.Opt(IDL.Nat),
    'fontFamily' : IDL.Opt(IDL.Text),
    'visible' : IDL.Bool,
    'fontSize' : IDL.Opt(IDL.Nat),
    'alignment' : IDL.Opt(Position),
  });
  const VorlageLayoutV2 = IDL.Record({
    'marginBottomMm' : IDL.Float64,
    'pageHeightMm' : IDL.Float64,
    'gridCols' : IDL.Nat,
    'gridRows' : IDL.Nat,
    'marginRightMm' : IDL.Float64,
    'marginTopMm' : IDL.Float64,
    'marginLeftMm' : IDL.Float64,
    'elements' : IDL.Vec(LayoutElement),
    'pageWidthMm' : IDL.Float64,
  });
  const Rechnungsvorlage = IDL.Record({
    'standardtexte' : Standardtexte,
    'layout' : VorlageLayout,
    'logoBlob' : IDL.Opt(ExternalBlob),
    'layoutV2' : IDL.Opt(VorlageLayoutV2),
    'updatedAt' : Timestamp,
    'kanzleiId' : KanzleiId,
  });
  const RetentionPolicyId = IDL.Text;
  const RetentionPolicy = IDL.Record({
    'id' : RetentionPolicyId,
    'retentionYears' : IDL.Nat,
    'categoryName' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'legalBasis' : IDL.Opt(IDL.Text),
    'isLocked' : IDL.Bool,
    'kanzleiId' : KanzleiId,
  });
  const SuperAdminWhitelistEntry = IDL.Record({
    'principal' : IDL.Principal,
    'addedAt' : Timestamp,
  });
  const SupportConversationWithMessages = IDL.Record({
    'messages' : IDL.Vec(SupportMessage),
    'conversation' : SupportConversation,
  });
  const Result_21 = IDL.Variant({
    'ok' : SupportConversationWithMessages,
    'err' : IDL.Text,
  });
  const TimerState = IDL.Record({
    'startTime' : IDL.Int,
    'userId' : IDL.Principal,
    'leistungId' : LeistungId,
    'baseDauer' : IDL.Nat,
  });
  const Result_13 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result_20 = IDL.Variant({ 'ok' : Role, 'err' : IDL.Text });
  const DataAccessAction = IDL.Variant({
    'loeschen' : IDL.Null,
    'lesen' : IDL.Null,
    'schreiben' : IDL.Null,
  });
  const RoleMigrationResult = IDL.Record({
    'principal' : IDL.Principal,
    'changed' : IDL.Bool,
    'previousRole' : Role,
    'newRole' : Role,
  });
  const MigrationSummary = IDL.Record({
    'convertedCount' : IDL.Nat,
    'results' : IDL.Vec(RoleMigrationResult),
    'unchangedCount' : IDL.Nat,
  });
  const Result_19 = IDL.Variant({ 'ok' : MigrationSummary, 'err' : IDL.Text });
  const PromotionResult = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'whitelistAdded' : IDL.Bool,
    'email' : IDL.Text,
    'changed' : IDL.Bool,
  });
  const Result_18 = IDL.Variant({ 'ok' : PromotionResult, 'err' : IDL.Text });
  const Result_16 = IDL.Variant({ 'ok' : Rechnungsvorlage, 'err' : IDL.Text });
  const Result_15 = IDL.Variant({
    'ok' : PendingRegistrationId,
    'err' : VerificationError,
  });
  const Result_14 = IDL.Variant({ 'ok' : TimerState, 'err' : IDL.Text });
  const Result_11 = IDL.Variant({ 'ok' : DataFlowEntry, 'err' : IDL.Text });
  const Result_10 = IDL.Variant({
    'ok' : DataInventoryEntry,
    'err' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : DsrRequest, 'err' : IDL.Text });
  const Result_8 = IDL.Variant({ 'ok' : KanzleiStammdaten, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : RetentionPolicy, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSuperAdmin' : IDL.Func([IDL.Principal], [Result_1], []),
    'addSupportMessage' : IDL.Func(
        [SupportConversationId, IDL.Text],
        [Result_27],
        [],
      ),
    'addZahlung' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_26], []),
    'archivierMandat' : IDL.Func([IDL.Text], [Result_1], []),
    'changeEmail' : IDL.Func([PendingRegistrationId, IDL.Text], [Result], []),
    'completeRegistration' : IDL.Func([PendingRegistrationId], [Result_25], []),
    'createAuslage' : IDL.Func(
        [IDL.Text, IDL.Text, AuslagenKategorie, IDL.Nat, IDL.Text],
        [Result_12],
        [],
      ),
    'createDsrRequest' : IDL.Func([DsrRequest], [DsrRequest], []),
    'createInviteLink' : IDL.Func([IDL.Text], [Result_17], []),
    'createKlient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'createLeistung' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_6],
        [],
      ),
    'createMandat' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          Auslagenregelung,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
        ],
        [Result_5],
        [],
      ),
    'createRechnung' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result_24],
        [],
      ),
    'createSupportConversation' : IDL.Func(
        [SupportCategory, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_3],
        [],
      ),
    'deactivateKanzlei' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteAuslage' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteKanzlei' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteKlient' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteLeistung' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteLeistungserbringer' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteMandat' : IDL.Func([IDL.Text], [Result_1], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'executeDeletion' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'exportAuditTrailCsv' : IDL.Func([AuditTrailFilter], [IDL.Text], ['query']),
    'exportAuditTrailPdf' : IDL.Func(
        [AuditTrailFilter],
        [IDL.Vec(IDL.Nat8)],
        ['query'],
      ),
    'exportKanzleienCsv' : IDL.Func([], [IDL.Text], ['query']),
    'exportKanzleienPdf' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'getActiveUsersPerMonth' : IDL.Func(
        [KanzleiId, IDL.Nat],
        [ActiveUsersYearReport],
        ['query'],
      ),
    'getAllActiveUsersPerMonth' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AllKanzleienActiveUsersReport)],
        ['query'],
      ),
    'getAllKanzleienOverview' : IDL.Func(
        [],
        [IDL.Vec(KanzleiOverview)],
        ['query'],
      ),
    'getAllSupportConversations' : IDL.Func([], [Result_23], []),
    'getAuditTrail' : IDL.Func(
        [AuditTrailFilter],
        [IDL.Vec(AuditLogEntry)],
        ['query'],
      ),
    'getAuslagen' : IDL.Func([AuslagenFilter], [IDL.Vec(Auslage)], ['query']),
    'getBudgetSummaries' : IDL.Func([], [IDL.Vec(BudgetSummary)], ['query']),
    'getBudgetSummary' : IDL.Func([MandatId], [Result_22], ['query']),
    'getConsentRecords' : IDL.Func(
        [KanzleiId],
        [IDL.Vec(ConsentRecord)],
        ['query'],
      ),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(Leistungserbringer)], ['query']),
    'getDashboardStats' : IDL.Func([KanzleiId], [DashboardStats], ['query']),
    'getDataFlows' : IDL.Func([KanzleiId], [IDL.Vec(DataFlowEntry)], ['query']),
    'getDataInventory' : IDL.Func(
        [KanzleiId],
        [IDL.Vec(DataInventoryEntry)],
        ['query'],
      ),
    'getDsgVersion' : IDL.Func([], [IDL.Opt(DsgVersion)], ['query']),
    'getDsrRequests' : IDL.Func([KanzleiId], [IDL.Vec(DsrRequest)], ['query']),
    'getGehaltReport' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(GehaltInfo)],
        ['query'],
      ),
    'getInviteLinks' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
    'getKanzlei' : IDL.Func([], [IDL.Opt(Kanzlei)], ['query']),
    'getKanzleiReport' : IDL.Func(
        [IDL.Nat, ReportPeriod],
        [FirmReport],
        ['query'],
      ),
    'getKanzleiStammdaten' : IDL.Func(
        [],
        [IDL.Opt(KanzleiStammdaten)],
        ['query'],
      ),
    'getKlient' : IDL.Func([IDL.Text], [IDL.Opt(Klient)], ['query']),
    'getKlienten' : IDL.Func([], [IDL.Vec(Klient)], ['query']),
    'getLeistungen' : IDL.Func(
        [LeistungFilter],
        [IDL.Vec(Leistung)],
        ['query'],
      ),
    'getLeistungserbringer' : IDL.Func(
        [],
        [IDL.Vec(Leistungserbringer)],
        ['query'],
      ),
    'getLeistungserbringerByKanzlei' : IDL.Func(
        [KanzleiId],
        [IDL.Vec(Leistungserbringer)],
        ['query'],
      ),
    'getLeistungserbringerReport' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Nat, ReportPeriod],
        [ProviderReport],
        ['query'],
      ),
    'getLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMandat' : IDL.Func([IDL.Text], [IDL.Opt(Mandat)], ['query']),
    'getMandate' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Mandat)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getMySupportConversations' : IDL.Func(
        [],
        [IDL.Vec(SupportConversation)],
        [],
      ),
    'getOrCreateUser' : IDL.Func([], [Result_2], []),
    'getPendingDeletions' : IDL.Func(
        [KanzleiId],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPendingRegistration' : IDL.Func(
        [PendingRegistrationId],
        [IDL.Opt(PendingRegistrationView)],
        ['query'],
      ),
    'getRechnung' : IDL.Func([IDL.Text], [IDL.Opt(Rechnung)], ['query']),
    'getRechnungen' : IDL.Func(
        [RechnungFilter],
        [IDL.Vec(Rechnung)],
        ['query'],
      ),
    'getRechnungsvorlage' : IDL.Func(
        [],
        [IDL.Opt(Rechnungsvorlage)],
        ['query'],
      ),
    'getRetentionPolicies' : IDL.Func(
        [KanzleiId],
        [IDL.Vec(RetentionPolicy)],
        ['query'],
      ),
    'getSuperAdmins' : IDL.Func(
        [],
        [IDL.Vec(SuperAdminWhitelistEntry)],
        ['query'],
      ),
    'getSupportConversation' : IDL.Func(
        [SupportConversationId],
        [Result_21],
        [],
      ),
    'getTimer' : IDL.Func([LeistungId], [IDL.Opt(TimerState)], ['query']),
    'getUnreadSupportCountForAdmin' : IDL.Func([], [Result_13], []),
    'getUnreadSupportCountForUser' : IDL.Func([], [IDL.Nat], []),
    'getUserRole' : IDL.Func([IDL.Principal], [Result_20], ['query']),
    'getZahlungen' : IDL.Func([], [IDL.Vec(Zahlung)], ['query']),
    'isSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTimers' : IDL.Func([], [IDL.Vec(TimerState)], ['query']),
    'logAuditEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'logDataAccess' : IDL.Func([IDL.Text, IDL.Text, DataAccessAction], [], []),
    'markSupportMessageRead' : IDL.Func(
        [SupportConversationId],
        [Result_1],
        [],
      ),
    'migrateRoles' : IDL.Func([], [Result_19], []),
    'promoteJoaoMarques' : IDL.Func([], [Result_18], []),
    'reactivateKanzlei' : IDL.Func([IDL.Text], [Result_1], []),
    'recordConsent' : IDL.Func([KlientId, IDL.Text], [ConsentRecord], []),
    'redeemInviteLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'registerKanzlei' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Zahlungsmodalitaet),
        ],
        [Result_17],
        [],
      ),
    'removeLeistungserbringer' : IDL.Func([IDL.Principal], [Result_1], []),
    'removeLogo' : IDL.Func([], [Result_1], []),
    'removeSuperAdmin' : IDL.Func([IDL.Principal], [Result_1], []),
    'saveRechnungsvorlage' : IDL.Func([Rechnungsvorlage], [Result_16], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendVerificationCode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Zahlungsmodalitaet),
        ],
        [Result_15],
        [],
      ),
    'startTimer' : IDL.Func([LeistungId, IDL.Nat], [Result_14], []),
    'stopTimer' : IDL.Func([LeistungId], [Result_13], []),
    'updateAuslage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_12], []),
    'updateDataFlowEntry' : IDL.Func(
        [DataFlowId, DataFlowEntry],
        [Result_11],
        [],
      ),
    'updateDataInventoryEntry' : IDL.Func(
        [DataInventoryId, DataInventoryEntry],
        [Result_10],
        [],
      ),
    'updateDsgVersion' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [DsgVersion],
        [],
      ),
    'updateDsrRequest' : IDL.Func(
        [DsrId, DsrStatus, IDL.Opt(IDL.Text)],
        [Result_9],
        [],
      ),
    'updateKanzleiStammdaten' : IDL.Func([KanzleiStammdaten], [Result_8], []),
    'updateKanzleiStundensatz' : IDL.Func([IDL.Nat], [Result_1], []),
    'updateKlient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'updateLeistung' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_6], []),
    'updateLeistungserbringer' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'updateMandat' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          Auslagenregelung,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
        ],
        [Result_5],
        [],
      ),
    'updateRetentionPolicy' : IDL.Func(
        [RetentionPolicyId, IDL.Nat, IDL.Bool],
        [Result_4],
        [],
      ),
    'updateSupportStatus' : IDL.Func(
        [SupportConversationId, SupportStatus],
        [Result_3],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'updateUserRole' : IDL.Func([IDL.Principal, Role], [Result_2], []),
    'updateZahlungsstatus' : IDL.Func(
        [IDL.Text, ZahlungsStatus],
        [Result_1],
        [],
      ),
    'uploadLogo' : IDL.Func([ExternalBlob], [Result_1], []),
    'verifyEmail' : IDL.Func([PendingRegistrationId, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };