/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AboModell = { 'jahres' : null } |
  { 'monats' : null } |
  { 'keine' : null };
export interface ActiveUserEntry {
  'userId' : Principal,
  'name' : string,
  'isActive' : boolean,
}
export interface ActiveUserMonth {
  'month' : bigint,
  'total' : bigint,
  'year' : bigint,
  'users' : Array<ActiveUserEntry>,
}
export interface ActiveUsersYearReport {
  'yearTotal' : bigint,
  'year' : bigint,
  'months' : Array<ActiveUserMonth>,
  'kanzleiId' : KanzleiId,
}
export interface AllKanzleienActiveUsersReport {
  'kanzleiName' : string,
  'yearTotal' : bigint,
  'year' : bigint,
  'months' : Array<ActiveUserMonth>,
  'kanzleiId' : KanzleiId,
}
export interface AuditLogEntry {
  'id' : AuditLogId,
  'action' : string,
  'entityId' : string,
  'afterValue' : [] | [string],
  'timestamp' : Timestamp,
  'beforeValue' : [] | [string],
  'actorPrincipal' : Principal,
  'entityType' : string,
  'kanzleiId' : KanzleiId,
}
export type AuditLogId = string;
export interface AuditTrailFilter {
  'toTimestamp' : [] | [Timestamp],
  'fromTimestamp' : [] | [Timestamp],
  'entityId' : [] | [string],
  'actorPrincipal' : [] | [Principal],
  'entityType' : [] | [string],
  'kanzleiId' : KanzleiId,
}
export interface Auslage {
  'id' : AuslageId,
  'status' : AuslagenStatus,
  'createdAt' : Timestamp,
  'leistungserbringerId' : Principal,
  'rechnungId' : [] | [RechnungId],
  'betrag' : bigint,
  'kategorie' : AuslagenKategorie,
  'beschreibung' : string,
  'datum' : string,
  'mandatId' : MandatId,
  'kanzleiId' : KanzleiId,
}
export type AuslageId = string;
export interface AuslagenFilter {
  'status' : [] | [AuslagenStatus],
  'datumBis' : [] | [string],
  'datumVon' : [] | [string],
  'leistungserbringerId' : [] | [Principal],
  'mandatId' : [] | [MandatId],
}
export type AuslagenKategorie = { 'andere' : null } |
  { 'porto' : null } |
  { 'reise' : null } |
  { 'kopien' : null };
export type AuslagenStatus = { 'offen' : null } |
  { 'verrechnet' : null };
export type Auslagenregelung = { 'Effektiv' : null } |
  { 'Keine' : null } |
  { 'Pauschal' : null };
export type BillingStatus = { 'offen' : null } |
  { 'bezahlt' : null } |
  { 'ueberfaellig' : null };
export interface BudgetSummary {
  'restbudget' : bigint,
  'totalAuslagen' : bigint,
  'totalHonorar' : bigint,
  'totalBudget' : bigint,
  'mandatId' : MandatId,
}
export interface Cell { 'value' : Value, 'name' : string }
export type ConsentId = string;
export interface ConsentRecord {
  'id' : ConsentId,
  'principal' : Principal,
  'dsgVersion' : string,
  'timestamp' : Timestamp,
  'consentGiven' : boolean,
  'klientId' : KlientId,
  'kanzleiId' : KanzleiId,
}
export interface DashboardStats {
  'pendingDeletions' : bigint,
  'auditExports' : bigint,
  'totalRecordsByCategory' : Array<[string, bigint]>,
  'openDsrRequests' : bigint,
  'missingConsents' : bigint,
}
export type DataAccessAction = { 'loeschen' : null } |
  { 'lesen' : null } |
  { 'schreiben' : null };
export interface DataFlowEntry {
  'id' : DataFlowId,
  'destination' : string,
  'what' : string,
  'isExternal' : boolean,
  'flowName' : string,
  'legalBasis' : string,
  'purpose' : string,
  'kanzleiId' : KanzleiId,
}
export type DataFlowId = string;
export interface DataInventoryEntry {
  'id' : DataInventoryId,
  'storageDuration' : string,
  'categoryName' : string,
  'accessRole' : Role,
  'description' : [] | [string],
  'storageLocation' : string,
  'kanzleiId' : KanzleiId,
}
export type DataInventoryId = string;
export interface DsgVersion {
  'content' : [] | [string],
  'publishedAt' : Timestamp,
  'version' : string,
}
export type DsrId = string;
export interface DsrRequest {
  'id' : DsrId,
  'status' : DsrStatus,
  'completedAt' : [] | [Timestamp],
  'dsrType' : DsrType,
  'assignedTo' : [] | [Principal],
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'requesterEmail' : string,
  'requesterName' : string,
  'kanzleiId' : KanzleiId,
  'requesterId' : [] | [KlientId],
}
export type DsrStatus = { 'inBearbeitung' : null } |
  { 'abgeschlossen' : null } |
  { 'erfasst' : null };
export type DsrType = { 'berichtigung' : null } |
  { 'loeschung' : null } |
  { 'auskunft' : null };
export type ExternalBlob = Uint8Array;
export interface FirmReport {
  'monthlyBreakdown' : Array<MonthlyTotal>,
  'totals' : MonthlyTotal,
}
export interface GehaltInfo {
  'leistungsbasiert' : bigint,
  'kanzleianteil' : bigint,
  'provider' : Leistungserbringer,
  'gesamtgehalt' : bigint,
  'akquisitionsboni' : bigint,
}
export interface GridArea {
  'col' : bigint,
  'row' : bigint,
  'rowSpan' : bigint,
  'colSpan' : bigint,
}
export interface InviteToken {
  'redeemedBy' : [] | [Principal],
  'token' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'email' : string,
  'kanzleiId' : KanzleiId,
}
export interface Kanzlei {
  'id' : KanzleiId,
  'defaultStundensatz' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'stammdaten' : [] | [KanzleiStammdaten],
  'zahlungsmodalitaet' : [] | [Zahlungsmodalitaet],
}
export type KanzleiId = string;
export interface KanzleiOverview {
  'id' : KanzleiId,
  'stammdatenAdresse' : string,
  'status' : string,
  'billingStatus' : BillingStatus,
  'stammdatenMwstNr' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'stammdatenUid' : string,
  'stammdatenKanzleiname' : string,
  'aboModell' : AboModell,
  'userCount' : bigint,
}
export interface KanzleiStammdaten {
  'ort' : string,
  'plz' : string,
  'uid' : string,
  'land' : string,
  'kanzleiname' : string,
  'strasseHausnummer' : string,
  'kanzleiLogoBlob' : [] | [Uint8Array],
  'mwstNr' : string,
  'email' : string,
  'website' : string,
  'telefon' : string,
}
export interface Klient {
  'id' : KlientId,
  'plzOrt' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'telefon' : string,
  'kanzleiId' : KanzleiId,
  'strasse' : string,
}
export type KlientId = string;
export interface LayoutElement {
  'id' : LayoutElementId,
  'xMm' : [] | [number],
  'yMm' : [] | [number],
  'italic' : [] | [boolean],
  'widthMm' : [] | [number],
  'heightMm' : [] | [number],
  'order' : bigint,
  'bold' : [] | [boolean],
  'gridArea' : GridArea,
  'zOrder' : [] | [bigint],
  'fontFamily' : [] | [string],
  'visible' : boolean,
  'fontSize' : [] | [bigint],
  'alignment' : [] | [Position],
}
export type LayoutElementId = { 'summenblock' : null } |
  { 'absenderadresse' : null } |
  { 'spesenAuslagen' : null } |
  { 'rechnungsmetadaten' : null } |
  { 'logo' : null } |
  { 'mandatsinfo' : null } |
  { 'fusszeile' : null } |
  { 'schlusstext' : null } |
  { 'einleitung' : null } |
  { 'empfaengeradresse' : null } |
  { 'leistungspositionen' : null } |
  { 'zahlungsinformationen' : null };
export interface Leistung {
  'id' : LeistungId,
  'status' : LeistungStatus,
  'taetigkeit' : string,
  'createdAt' : Timestamp,
  'leistungserbringerId' : Principal,
  'rechnungId' : [] | [RechnungId],
  'datum' : string,
  'dauer' : bigint,
  'honorar' : bigint,
  'mandatId' : MandatId,
  'kanzleiId' : KanzleiId,
}
export interface LeistungFilter {
  'status' : [] | [LeistungStatus],
  'datumBis' : [] | [string],
  'datumVon' : [] | [string],
  'leistungserbringerId' : [] | [Principal],
  'mandatId' : [] | [MandatId],
}
export type LeistungId = string;
export type LeistungStatus = { 'offen' : null } |
  { 'verrechnet' : null };
export interface Leistungserbringer {
  'id' : Principal,
  'status' : string,
  'titel' : string,
  'nachname' : string,
  'role' : [] | [Role],
  'statusHistory' : Array<StatusHistoryEntry>,
  'email' : string,
  'vorname' : string,
  'isAdmin' : boolean,
  'registeredAt' : Timestamp,
  'kanzleiId' : KanzleiId,
}
export interface Mandat {
  'id' : MandatId,
  'status' : MandatStatus,
  'rundungAktiv' : boolean,
  'bezeichnung' : string,
  'kostenProScan' : number,
  'auslagenregelung' : Auslagenregelung,
  'createdAt' : Timestamp,
  'kostenProKopie' : number,
  'leistungenAusweisen' : boolean,
  'portoEinschreiben' : number,
  'portoBPost' : number,
  'akquisitionsbonus' : bigint,
  'pauschalBetrag' : bigint,
  'mwstSatz' : bigint,
  'standardStundensatz' : bigint,
  'zahlungsbedingungen' : string,
  'akquisiteurId' : Principal,
  'budget' : bigint,
  'autokilometer' : number,
  'klientId' : KlientId,
  'waehrung' : string,
  'portoAPost' : number,
  'kanzleiId' : KanzleiId,
}
export type MandatId = string;
export type MandatStatus = { 'archiviert' : null } |
  { 'aktiv' : null };
export interface MigrationSummary {
  'convertedCount' : bigint,
  'results' : Array<RoleMigrationResult>,
  'unchangedCount' : bigint,
}
export interface MonthlyTotal {
  'month' : bigint,
  'total' : bigint,
  'auslagen' : bigint,
  'year' : bigint,
  'verrechnete' : bigint,
  'honorar' : bigint,
}
export type PendingRegistrationId = string;
export interface PendingRegistrationView {
  'id' : PendingRegistrationId,
  'titel' : string,
  'nachname' : string,
  'emailVerified' : boolean,
  'kanzleiName' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'vorname' : string,
  'zahlungsmodalitaet' : [] | [Zahlungsmodalitaet],
  'verifiedAt' : [] | [Timestamp],
}
export type Position = { 'zentriert' : null } |
  { 'links' : null } |
  { 'rechts' : null };
export interface PromotionResult {
  'principal' : [] | [Principal],
  'whitelistAdded' : boolean,
  'email' : string,
  'changed' : boolean,
}
export interface ProviderComparison {
  'total' : bigint,
  'provider' : Leistungserbringer,
}
export interface ProviderReport {
  'monthlyBreakdown' : Array<MonthlyTotal>,
  'totals' : MonthlyTotal,
  'comparisonData' : Array<ProviderComparison>,
}
export interface Rechnung {
  'id' : RechnungId,
  'rechnungsnummer' : string,
  'total' : bigint,
  'rechnungsdatum' : string,
  'createdAt' : Timestamp,
  'mwstBetrag' : bigint,
  'leistungserbringerId' : Principal,
  'faelligkeitsdatum' : string,
  'zahlungsstatus' : ZahlungsStatus,
  'zahlungsbedingungen' : string,
  'leistungszeitraumBis' : string,
  'leistungszeitraumVon' : string,
  'leistungspositionen' : Array<LeistungId>,
  'auslageIds' : Array<AuslageId>,
  'waehrung' : string,
  'mandatId' : MandatId,
  'kanzleiId' : KanzleiId,
  'subtotal' : bigint,
}
export interface RechnungFilter {
  'datumBis' : [] | [string],
  'datumVon' : [] | [string],
  'zahlungsstatus' : [] | [ZahlungsStatus],
  'akquisiteurId' : [] | [Principal],
  'mandatId' : [] | [MandatId],
}
export type RechnungId = string;
export interface Rechnungsvorlage {
  'standardtexte' : Standardtexte,
  'layout' : VorlageLayout,
  'logoBlob' : [] | [ExternalBlob],
  'layoutV2' : [] | [VorlageLayoutV2],
  'updatedAt' : Timestamp,
  'kanzleiId' : KanzleiId,
}
export type ReportPeriod = { 'monatlich' : bigint } |
  { 'jaehrlich' : null };
export type Result = { 'ok' : null } |
  { 'err' : VerificationError };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_10 = { 'ok' : DataInventoryEntry } |
  { 'err' : string };
export type Result_11 = { 'ok' : DataFlowEntry } |
  { 'err' : string };
export type Result_12 = { 'ok' : Auslage } |
  { 'err' : string };
export type Result_13 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_14 = { 'ok' : TimerState } |
  { 'err' : string };
export type Result_15 = { 'ok' : PendingRegistrationId } |
  { 'err' : VerificationError };
export type Result_16 = { 'ok' : Rechnungsvorlage } |
  { 'err' : string };
export type Result_17 = { 'ok' : string } |
  { 'err' : string };
export type Result_18 = { 'ok' : PromotionResult } |
  { 'err' : string };
export type Result_19 = { 'ok' : MigrationSummary } |
  { 'err' : string };
export type Result_2 = { 'ok' : Leistungserbringer } |
  { 'err' : string };
export type Result_20 = { 'ok' : Role } |
  { 'err' : string };
export type Result_21 = { 'ok' : SupportConversationWithMessages } |
  { 'err' : string };
export type Result_22 = { 'ok' : BudgetSummary } |
  { 'err' : string };
export type Result_23 = { 'ok' : Array<SupportConversation> } |
  { 'err' : string };
export type Result_24 = { 'ok' : Rechnung } |
  { 'err' : string };
export type Result_25 = { 'ok' : KanzleiId } |
  { 'err' : VerificationError };
export type Result_26 = { 'ok' : Zahlung } |
  { 'err' : string };
export type Result_27 = { 'ok' : SupportMessage } |
  { 'err' : string };
export type Result_3 = { 'ok' : SupportConversation } |
  { 'err' : string };
export type Result_4 = { 'ok' : RetentionPolicy } |
  { 'err' : string };
export type Result_5 = { 'ok' : Mandat } |
  { 'err' : string };
export type Result_6 = { 'ok' : Leistung } |
  { 'err' : string };
export type Result_7 = { 'ok' : Klient } |
  { 'err' : string };
export type Result_8 = { 'ok' : KanzleiStammdaten } |
  { 'err' : string };
export type Result_9 = { 'ok' : DsrRequest } |
  { 'err' : string };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface RetentionPolicy {
  'id' : RetentionPolicyId,
  'retentionYears' : bigint,
  'categoryName' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'legalBasis' : [] | [string],
  'isLocked' : boolean,
  'kanzleiId' : KanzleiId,
}
export type RetentionPolicyId = string;
export type Role = { 'mandant' : null } |
  { 'admin' : null } |
  { 'mitarbeiter' : null } |
  { 'plattform_admin' : null } |
  { 'anwalt' : null };
export interface RoleMigrationResult {
  'principal' : Principal,
  'changed' : boolean,
  'previousRole' : Role,
  'newRole' : Role,
}
export interface Standardtexte {
  'rechnungstitel' : string,
  'zahlungshinweis' : string,
  'schlusstext' : string,
  'einleitung' : string,
}
export interface StatusHistoryEntry {
  'status' : string,
  'month' : bigint,
  'year' : bigint,
}
export interface SuperAdminWhitelistEntry {
  'principal' : Principal,
  'addedAt' : Timestamp,
}
export type SupportCategory = { 'frage' : null } |
  { 'fehler' : null } |
  { 'feedback' : null } |
  { 'verbesserungsvorschlag' : null };
export interface SupportConversation {
  'id' : SupportConversationId,
  'status' : SupportStatus,
  'appRoute' : string,
  'subject' : string,
  'createdByUserId' : string,
  'createdAt' : bigint,
  'appVersion' : string,
  'updatedAt' : bigint,
  'category' : SupportCategory,
  'kanzleiId' : KanzleiId,
  'createdByUserName' : string,
}
export type SupportConversationId = string;
export interface SupportConversationWithMessages {
  'messages' : Array<SupportMessage>,
  'conversation' : SupportConversation,
}
export interface SupportMessage {
  'id' : SupportMessageId,
  'senderUserName' : string,
  'createdAt' : bigint,
  'conversationId' : SupportConversationId,
  'message' : string,
  'senderType' : SupportSenderType,
  'senderUserId' : string,
  'readAt' : [] | [bigint],
}
export type SupportMessageId = string;
export type SupportSenderType = { 'user' : null } |
  { 'platformAdmin' : null };
export type SupportStatus = { 'neu' : null } |
  { 'archiviert' : null } |
  { 'erledigt' : null } |
  { 'in_bearbeitung' : null };
export interface TimerState {
  'startTime' : bigint,
  'userId' : Principal,
  'leistungId' : LeistungId,
  'baseDauer' : bigint,
}
export type Timestamp = bigint;
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerificationError = { 'codeExpired' : null } |
  { 'tooManyAttempts' : null } |
  { 'principalAlreadyUsed' : null } |
  { 'invalidInput' : null } |
  { 'sendFailed' : null } |
  { 'notFound' : null } |
  { 'invalidCode' : null } |
  { 'alreadyRegistered' : null } |
  { 'emailAlreadyVerified' : null } |
  { 'resendTooSoon' : null };
export interface VorlageLayout {
  'logoPosition' : Position,
  'empfaengerPosition' : Position,
  'fusszeile' : string,
  'absenderPosition' : Position,
}
export interface VorlageLayoutV2 {
  'marginBottomMm' : number,
  'pageHeightMm' : number,
  'gridCols' : bigint,
  'gridRows' : bigint,
  'marginRightMm' : number,
  'marginTopMm' : number,
  'marginLeftMm' : number,
  'elements' : Array<LayoutElement>,
  'pageWidthMm' : number,
}
export interface Zahlung {
  'id' : ZahlungId,
  'status' : ZahlungEingangStatus,
  'createdAt' : Timestamp,
  'rechnungId' : RechnungId,
  'betrag' : bigint,
  'datum' : string,
  'kanzleiId' : KanzleiId,
}
export type ZahlungEingangStatus = { 'eingegangen' : null } |
  { 'bestaetigt' : null };
export type ZahlungId = string;
export type ZahlungsStatus = { 'offen' : null } |
  { 'bezahlt' : null } |
  { 'ueberfaellig' : null };
export type Zahlungsmodalitaet = { 'jahres' : null } |
  { 'monats' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addSuperAdmin' : ActorMethod<[Principal], Result_1>,
  'addSupportMessage' : ActorMethod<[SupportConversationId, string], Result_27>,
  'addZahlung' : ActorMethod<[string, string, bigint], Result_26>,
  'archivierMandat' : ActorMethod<[string], Result_1>,
  'changeEmail' : ActorMethod<[PendingRegistrationId, string], Result>,
  'completeRegistration' : ActorMethod<[PendingRegistrationId], Result_25>,
  'createAuslage' : ActorMethod<
    [string, string, AuslagenKategorie, bigint, string],
    Result_12
  >,
  'createDsrRequest' : ActorMethod<[DsrRequest], DsrRequest>,
  'createInviteLink' : ActorMethod<[string], Result_17>,
  'createKlient' : ActorMethod<
    [string, string, string, string, string],
    Result_7
  >,
  'createLeistung' : ActorMethod<[string, string, string, bigint], Result_6>,
  'createMandat' : ActorMethod<
    [
      string,
      string,
      Principal,
      bigint,
      bigint,
      bigint,
      boolean,
      Auslagenregelung,
      bigint,
      string,
      string,
      bigint,
      number,
      number,
      number,
      number,
      number,
      number,
      boolean,
    ],
    Result_5
  >,
  'createRechnung' : ActorMethod<
    [string, Array<string>, Array<string>, string, string, string, string],
    Result_24
  >,
  'createSupportConversation' : ActorMethod<
    [SupportCategory, string, string, string, string],
    Result_3
  >,
  'deactivateKanzlei' : ActorMethod<[string], Result_1>,
  'deleteAuslage' : ActorMethod<[string], Result_1>,
  'deleteKanzlei' : ActorMethod<[string], Result_1>,
  'deleteKlient' : ActorMethod<[string], Result_1>,
  'deleteLeistung' : ActorMethod<[string], Result_1>,
  'deleteLeistungserbringer' : ActorMethod<[string], Result_1>,
  'deleteMandat' : ActorMethod<[string], Result_1>,
  'execute' : ActorMethod<[string], Result__1>,
  'executeDeletion' : ActorMethod<[string, string], Result_1>,
  'exportAuditTrailCsv' : ActorMethod<[AuditTrailFilter], string>,
  'exportAuditTrailPdf' : ActorMethod<[AuditTrailFilter], Uint8Array>,
  'exportKanzleienCsv' : ActorMethod<[], string>,
  'exportKanzleienPdf' : ActorMethod<[], Uint8Array>,
  'getActiveUsersPerMonth' : ActorMethod<
    [KanzleiId, bigint],
    ActiveUsersYearReport
  >,
  'getAllActiveUsersPerMonth' : ActorMethod<
    [bigint],
    Array<AllKanzleienActiveUsersReport>
  >,
  'getAllKanzleienOverview' : ActorMethod<[], Array<KanzleiOverview>>,
  'getAllSupportConversations' : ActorMethod<[], Result_23>,
  'getAuditTrail' : ActorMethod<[AuditTrailFilter], Array<AuditLogEntry>>,
  'getAuslagen' : ActorMethod<[AuslagenFilter], Array<Auslage>>,
  'getBudgetSummaries' : ActorMethod<[], Array<BudgetSummary>>,
  'getBudgetSummary' : ActorMethod<[MandatId], Result_22>,
  'getConsentRecords' : ActorMethod<[KanzleiId], Array<ConsentRecord>>,
  'getCurrentUser' : ActorMethod<[], [] | [Leistungserbringer]>,
  'getDashboardStats' : ActorMethod<[KanzleiId], DashboardStats>,
  'getDataFlows' : ActorMethod<[KanzleiId], Array<DataFlowEntry>>,
  'getDataInventory' : ActorMethod<[KanzleiId], Array<DataInventoryEntry>>,
  'getDsgVersion' : ActorMethod<[], [] | [DsgVersion]>,
  'getDsrRequests' : ActorMethod<[KanzleiId], Array<DsrRequest>>,
  'getGehaltReport' : ActorMethod<[bigint, [] | [bigint]], Array<GehaltInfo>>,
  'getInviteLinks' : ActorMethod<[], Array<InviteToken>>,
  'getKanzlei' : ActorMethod<[], [] | [Kanzlei]>,
  'getKanzleiReport' : ActorMethod<[bigint, ReportPeriod], FirmReport>,
  'getKanzleiStammdaten' : ActorMethod<[], [] | [KanzleiStammdaten]>,
  'getKlient' : ActorMethod<[string], [] | [Klient]>,
  'getKlienten' : ActorMethod<[], Array<Klient>>,
  'getLeistungen' : ActorMethod<[LeistungFilter], Array<Leistung>>,
  'getLeistungserbringer' : ActorMethod<[], Array<Leistungserbringer>>,
  'getLeistungserbringerByKanzlei' : ActorMethod<
    [KanzleiId],
    Array<Leistungserbringer>
  >,
  'getLeistungserbringerReport' : ActorMethod<
    [[] | [Principal], bigint, ReportPeriod],
    ProviderReport
  >,
  'getLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMandat' : ActorMethod<[string], [] | [Mandat]>,
  'getMandate' : ActorMethod<[[] | [string]], Array<Mandat>>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getMySupportConversations' : ActorMethod<[], Array<SupportConversation>>,
  'getOrCreateUser' : ActorMethod<[], Result_2>,
  'getPendingDeletions' : ActorMethod<
    [KanzleiId],
    Array<[string, string, bigint]>
  >,
  'getPendingRegistration' : ActorMethod<
    [PendingRegistrationId],
    [] | [PendingRegistrationView]
  >,
  'getRechnung' : ActorMethod<[string], [] | [Rechnung]>,
  'getRechnungen' : ActorMethod<[RechnungFilter], Array<Rechnung>>,
  'getRechnungsvorlage' : ActorMethod<[], [] | [Rechnungsvorlage]>,
  'getRetentionPolicies' : ActorMethod<[KanzleiId], Array<RetentionPolicy>>,
  'getSuperAdmins' : ActorMethod<[], Array<SuperAdminWhitelistEntry>>,
  'getSupportConversation' : ActorMethod<[SupportConversationId], Result_21>,
  'getTimer' : ActorMethod<[LeistungId], [] | [TimerState]>,
  'getUnreadSupportCountForAdmin' : ActorMethod<[], Result_13>,
  'getUnreadSupportCountForUser' : ActorMethod<[], bigint>,
  'getUserRole' : ActorMethod<[Principal], Result_20>,
  'getZahlungen' : ActorMethod<[], Array<Zahlung>>,
  'isSuperAdmin' : ActorMethod<[], boolean>,
  'listTimers' : ActorMethod<[], Array<TimerState>>,
  'logAuditEntry' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'logDataAccess' : ActorMethod<[string, string, DataAccessAction], undefined>,
  'markSupportMessageRead' : ActorMethod<[SupportConversationId], Result_1>,
  'migrateRoles' : ActorMethod<[], Result_19>,
  'promoteJoaoMarques' : ActorMethod<[], Result_18>,
  'reactivateKanzlei' : ActorMethod<[string], Result_1>,
  'recordConsent' : ActorMethod<[KlientId, string], ConsentRecord>,
  'redeemInviteLink' : ActorMethod<
    [string, string, string, string, string],
    Result_2
  >,
  'registerKanzlei' : ActorMethod<
    [string, string, string, string, string, [] | [Zahlungsmodalitaet]],
    Result_17
  >,
  'removeLeistungserbringer' : ActorMethod<[Principal], Result_1>,
  'removeLogo' : ActorMethod<[], Result_1>,
  'removeSuperAdmin' : ActorMethod<[Principal], Result_1>,
  'saveRechnungsvorlage' : ActorMethod<[Rechnungsvorlage], Result_16>,
  'schema' : ActorMethod<[], string>,
  'sendVerificationCode' : ActorMethod<
    [string, string, string, string, string, [] | [Zahlungsmodalitaet]],
    Result_15
  >,
  'startTimer' : ActorMethod<[LeistungId, bigint], Result_14>,
  'stopTimer' : ActorMethod<[LeistungId], Result_13>,
  'updateAuslage' : ActorMethod<[string, string, bigint], Result_12>,
  'updateDataFlowEntry' : ActorMethod<[DataFlowId, DataFlowEntry], Result_11>,
  'updateDataInventoryEntry' : ActorMethod<
    [DataInventoryId, DataInventoryEntry],
    Result_10
  >,
  'updateDsgVersion' : ActorMethod<[string, [] | [string]], DsgVersion>,
  'updateDsrRequest' : ActorMethod<[DsrId, DsrStatus, [] | [string]], Result_9>,
  'updateKanzleiStammdaten' : ActorMethod<[KanzleiStammdaten], Result_8>,
  'updateKanzleiStundensatz' : ActorMethod<[bigint], Result_1>,
  'updateKlient' : ActorMethod<
    [string, string, string, string, string, string],
    Result_7
  >,
  'updateLeistung' : ActorMethod<[string, string, bigint], Result_6>,
  'updateLeistungserbringer' : ActorMethod<
    [Principal, string, string, string],
    Result_1
  >,
  'updateMandat' : ActorMethod<
    [
      string,
      string,
      Principal,
      bigint,
      bigint,
      bigint,
      boolean,
      Auslagenregelung,
      bigint,
      string,
      string,
      bigint,
      number,
      number,
      number,
      number,
      number,
      number,
      boolean,
    ],
    Result_5
  >,
  'updateRetentionPolicy' : ActorMethod<
    [RetentionPolicyId, bigint, boolean],
    Result_4
  >,
  'updateSupportStatus' : ActorMethod<
    [SupportConversationId, SupportStatus],
    Result_3
  >,
  'updateUserProfile' : ActorMethod<[string, string], Result_1>,
  'updateUserRole' : ActorMethod<[Principal, Role], Result_2>,
  'updateZahlungsstatus' : ActorMethod<[string, ZahlungsStatus], Result_1>,
  'uploadLogo' : ActorMethod<[ExternalBlob], Result_1>,
  'verifyEmail' : ActorMethod<[PendingRegistrationId, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];